"""type-10022026-Maurice: Authentication API routes."""
from django.urls import path
from . import views
from .smart import DeveloperAppsView, DeveloperAppRevokeView, AuthorizationView, TokenView, RevokeTokenView, LaunchView, PatientSelectionView, smart_configuration

urlpatterns = [
    path("auth/login/", views.login_view), path("auth/enroll/", views.enroll_view),
    path("auth/enroll/verify/", views.verify_enrollment_view), path("auth/session/", views.session_view),
    path("auth/logout/", views.logout_view), path("shell/", views.shell_view),
    path("auth/passkeys/options/", views.passkey_options_view),
    path("auth/passkeys/register/", views.passkey_register_view),
    path("auth/passkeys/login/options/", views.passkey_login_options_view),
    path("auth/passkeys/login/", views.passkey_login_view),
    path("auth/passkeys/", views.passkey_list_view),
    path("auth/passkeys/<int:credential_id>/", views.passkey_manage_view),
    path("auth/recovery/request/", views.recovery_request_view),
    path("auth/recovery/verify/", views.recovery_verify_view),
    path("patients/", views.PatientCollectionView.as_view()),
    path("patients/<str:public_id>/", views.PatientDetailView.as_view()),
    path("patients/<str:public_id>/break-glass/", views.BreakGlassView.as_view()),
    path("admin/break-glass/", views.BreakGlassReviewView.as_view()),
    path("admin/break-glass/<int:grant_id>/", views.BreakGlassReviewView.as_view()),
    path("patients/<str:public_id>/exports/", views.PatientExportView.as_view()),
    path("patients/<str:public_id>/exports/<uuid:artifact_id>/", views.PatientExportView.as_view()),
    path("exports/<uuid:artifact_id>/download/", views.PatientExportDownloadView.as_view()),
    path("patients/<str:public_id>/devices/", views.DeviceCollectionView.as_view()),
    path("patients/<str:public_id>/devices/parse/", views.DeviceParseView.as_view()),
    path("patients/<str:public_id>/devices/<int:device_id>/", views.DeviceDetailView.as_view()),
    path("patients/<str:public_id>/devices/<int:device_id>/history/", views.DeviceHistoryView.as_view()),
    path("patients/<str:public_id>/family-history/", views.FamilyHistoryCollectionView.as_view()),
    path("patients/<str:public_id>/family-history/<int:history_id>/", views.FamilyHistoryDetailView.as_view()),
    path("patients/<str:public_id>/family-history/<int:history_id>/history/", views.FamilyHistoryHistoryView.as_view()),
    path("patients/<str:public_id>/medications/", views.MedicationCollectionView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/", views.MedicationDetailView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/history/", views.MedicationHistoryView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/cancel/", views.MedicationCancelView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/refill/", views.MedicationRefillView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/evaluate/", views.MedicationEvaluateView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/acknowledge/", views.MedicationAcknowledgeView.as_view()),
    path("patients/<str:public_id>/medications/<int:order_id>/sign/", views.MedicationSignView.as_view()),
    path("admin/interaction-rules/", views.InteractionRuleAdminView.as_view()),
    path("admin/interaction-rules/<int:rule_id>/", views.InteractionRuleDetailAdminView.as_view()),
    path("admin/users/", views.AdminUserView.as_view()),
    path("admin/users/<int:user_id>/", views.AdminUserDetailView.as_view()),
    path("audit/", views.AuditReportView.as_view()),
    path("audit/verify/", views.AuditVerifyView.as_view()),
    path("jobs/", views.JobCollectionView.as_view()),
    path("jobs/<uuid:job_id>/", views.JobAdminView.as_view()),
    path("jobs/<uuid:job_id>/cancel/", views.JobAdminView.as_view()),
    path("admin/population-exports/", views.PopulationExportCollectionView.as_view()),
    path("admin/population-exports/<uuid:artifact_id>/", views.PopulationExportDetailView.as_view()),
    path("admin/population-exports/<uuid:artifact_id>/download/", views.PopulationExportDownloadView.as_view()),
    path("questionnaires/", views.QuestionnaireCollectionView.as_view()),
    path("questionnaires/<int:questionnaire_id>/", views.QuestionnaireDetailView.as_view()),
    path("patients/<str:public_id>/questionnaire-responses/", views.QuestionnaireResponseCollectionView.as_view()),
    path("patients/<str:public_id>/questionnaire-responses/<int:response_id>/", views.QuestionnaireResponseDetailView.as_view()),
    path("patients/<str:public_id>/amendments/", views.PatientAmendmentCollectionView.as_view()),
    path("amendments/", views.PatientAmendmentCollectionView.as_view()),
    path("amendments/<int:amendment_id>/", views.PatientAmendmentDetailView.as_view()),
    path("questionnaire-review-queue/", views.QuestionnaireReviewQueueView.as_view()),
    path("questionnaire-response-versions/<int:response_version_id>/review/", views.QuestionnaireReviewView.as_view()),
    path("smart/apps/", DeveloperAppsView.as_view()),
    path("smart/apps/<str:client_id>/", DeveloperAppRevokeView.as_view()),
    path("smart-configuration/", smart_configuration),
    path("oauth/authorize/", AuthorizationView.as_view()),
    path("oauth/token/", TokenView.as_view()),
    path("oauth/revoke_token/", RevokeTokenView.as_view()),
    path("smart/launch/", LaunchView.as_view()),
    path("smart/patient-selection/", PatientSelectionView.as_view()),
]
