"""Ticket 07 WebAuthn/recovery expansion coverage.

Each test name is intentionally one-to-one with a CSV case.  The WebAuthn
options are generated by the installed library; verifier-heavy paths use
deterministic server state so malformed input never needs a private key.
"""
import hashlib
import json

import pytest
import pyotp
from django.test import Client
from django.utils import timezone

from backend.users import passkeys
from backend.users.models import SmsRecoveryChallenge, User, WebAuthnChallenge, WebAuthnCredential


def _user(username="ticket07-user", role="clinician", totp=True):
    user = User.objects.create_user(username=username, password="pw", role=role,
                                    totp_enrolled=totp, totp_secret=pyotp.random_base32())
    return user


def _mfa_login(client, user):
    client.force_login(user)
    session = client.session
    session["mfa_generation"] = user.mfa_generation
    session.save()


@pytest.mark.django_db
def test_TC_EXP_0086_registration_options_are_bound_and_secret_free(client, settings):
    user = _user("tc-0086")
    _mfa_login(client, user)
    response = client.get("/api/auth/passkeys/options/")
    assert response.status_code == 200
    options = response.json()
    assert options["rp"]["id"] == settings.WEBAUTHN_RP_ID
    assert options["challenge"]
    challenge = WebAuthnChallenge.objects.get(user=user, ceremony="register")
    assert challenge.challenge_hash not in response.content.decode()
    assert "private" not in response.content.decode().lower()


@pytest.mark.django_db
def test_TC_EXP_0087_multiple_credentials_rename_and_revoke(client):
    user = _user("tc-0087")
    _mfa_login(client, user)
    first = WebAuthnCredential.objects.create(user=user, credential_id=b"credential-a", public_key=b"public-a", name="Laptop")
    second = WebAuthnCredential.objects.create(user=user, credential_id=b"credential-b", public_key=b"public-b", name="Phone")
    assert client.patch(f"/api/auth/passkeys/{first.pk}/", data=json.dumps({"name": "Office laptop"}), content_type="application/json").status_code == 200
    assert client.delete(f"/api/auth/passkeys/{second.pk}/").status_code == 204
    assert list(client.get("/api/auth/passkeys/").json())[0]["name"] == "Office laptop"
    second.refresh_from_db()
    assert second.revoked_at is not None


@pytest.mark.django_db
def test_TC_EXP_0088_challenge_replay_expiry_and_session_binding(client):
    user = _user("tc-0088")
    _mfa_login(client, user)
    options = client.get("/api/auth/passkeys/options/").json()
    challenge = WebAuthnChallenge.objects.get(user=user, ceremony="register")
    with pytest.raises(ValueError, match="expired_or_replayed_challenge"):
        passkeys.consume(client, b"wrong", "register", user)
    challenge.used_at = timezone.now()
    challenge.save(update_fields=["used_at"])
    assert client.post("/api/auth/passkeys/register/", {"challenge": options["challenge"], "credential": {}}).status_code == 400
    assert client.session.get("_auth_user_id") == str(user.pk)


@pytest.mark.django_db
def test_TC_EXP_0089_counter_regression_is_rejected(monkeypatch):
    user = _user("tc-0089")
    credential = WebAuthnCredential.objects.create(user=user, credential_id=b"counter-id", public_key=b"public", sign_count=8)
    class Verified:
        new_sign_count = 7
        user_verified = True
        credential_backed_up = False
    monkeypatch.setattr(passkeys, "consume", lambda *args: None)
    monkeypatch.setattr(passkeys.webauthn, "verify_authentication_response", lambda **kwargs: Verified())
    request = Client().get("/")
    request.user = user
    request.session = Client().session
    with pytest.raises(ValueError, match="counter_regression"):
        passkeys.verify_authentication(request, {"challenge": passkeys._b64(b"challenge"), "credential": {"rawId": passkeys._b64(b"counter-id")}}, user)
    credential.refresh_from_db()
    assert credential.sign_count == 8


@pytest.mark.django_db
def test_TC_EXP_0090_web_authn_secret_redaction(client, caplog):
    user = _user("tc-0090")
    _mfa_login(client, user)
    response = client.get("/api/auth/passkeys/options/")
    assert response.status_code == 200
    assert "challenge_hash" not in response.content.decode()
    assert all("private" not in record.getMessage().lower() for record in caplog.records)


@pytest.mark.django_db
def test_TC_EXP_0091_expired_challenge_is_single_use(client):
    user = _user("tc-0091")
    _mfa_login(client, user)
    first = client.get("/api/auth/passkeys/options/").json()["challenge"]
    challenge = WebAuthnChallenge.objects.get(user=user, ceremony="register")
    challenge.expires_at = timezone.now()
    challenge.save(update_fields=["expires_at"])
    assert client.post("/api/auth/passkeys/register/", {"challenge": first, "credential": {}}).status_code == 400
    second = client.get("/api/auth/passkeys/options/").json()["challenge"]
    assert second != first
    assert WebAuthnCredential.objects.filter(user=user).count() == 0


@pytest.mark.django_db
def test_TC_EXP_0092_totp_fallback_remains_available(client):
    user = _user("tc-0092")
    response = client.post("/api/auth/login/", {"username": user.username, "password": "pw", "otp": pyotp.TOTP(user.totp_secret).now()})
    assert response.status_code == 200
    assert response.json()["role"] == user.role
    assert not WebAuthnCredential.objects.filter(user=user).exists()


@pytest.mark.django_db
def test_TC_EXP_0093_sms_recovery_is_rate_limited_expiring_and_single_use(client, settings):
    user = _user("tc-0093", role="patient")
    user.recovery_phone_hash = hashlib.sha256(b"5550100").hexdigest()
    user.save(update_fields=["recovery_phone_hash"])
    response = client.post("/api/auth/recovery/request/", {"username": user.username, "password": "pw", "phone": "5550100"})
    assert response.status_code == 200 and "code" not in response.json()
    for _ in range(2):
        assert client.post("/api/auth/recovery/request/", {"username": user.username, "password": "pw", "phone": "5550100"}).status_code == 200
    assert client.post("/api/auth/recovery/request/", {"username": user.username, "password": "pw", "phone": "5550100"}).status_code == 429
    challenge = SmsRecoveryChallenge.objects.get(pk=response.json()["recovery_id"])
    code = hashlib.sha256(f"{user.pk}:{user.username}".encode()).hexdigest()[:6]
    assert client.post("/api/auth/recovery/verify/", {"recovery_id": challenge.pk, "code": code}).status_code == 200
    assert client.post("/api/auth/recovery/verify/", {"recovery_id": challenge.pk, "code": code}).status_code == 400
    challenge = SmsRecoveryChallenge.objects.create(user=user, code_hash=hashlib.sha256(b"x").hexdigest(), expires_at=timezone.now(), delivery_reference="sms-test")
    assert client.post("/api/auth/recovery/verify/", {"recovery_id": challenge.pk, "code": "x"}).status_code == 400


@pytest.mark.django_db
def test_TC_EXP_0094_recovery_invalidates_mfa_state(client):
    user = _user("tc-0094", role="patient")
    user.recovery_phone_hash = hashlib.sha256(b"5550100").hexdigest()
    user.save(update_fields=["recovery_phone_hash"])
    _mfa_login(client, user)
    generation = user.mfa_generation
    request = client.post("/api/auth/recovery/request/", {"username": user.username, "password": "pw", "phone": "5550100"})
    challenge = SmsRecoveryChallenge.objects.get(pk=request.json()["recovery_id"])
    code = hashlib.sha256(f"{user.pk}:{user.username}".encode()).hexdigest()[:6]
    assert client.post("/api/auth/recovery/verify/", {"recovery_id": challenge.pk, "code": code}).status_code == 200
    user.refresh_from_db()
    assert user.mfa_generation == generation + 1 and not user.totp_enrolled
    assert client.get("/api/auth/session/").status_code in {401, 403}


@pytest.mark.django_db
def test_TC_EXP_0095_recovery_audit_failure_rolls_back(monkeypatch, client):
    user = _user("tc-0095", role="patient")
    user.recovery_phone_hash = hashlib.sha256(b"5550100").hexdigest()
    user.save(update_fields=["recovery_phone_hash"])
    client.defaults["REMOTE_ADDR"] = "10.0.0.95"
    response = client.post("/api/auth/recovery/request/", {"username": user.username, "password": "pw", "phone": "5550100"})
    challenge = SmsRecoveryChallenge.objects.get(pk=response.json()["recovery_id"])
    monkeypatch.setattr("backend.users.views.audit.append_audit_event", lambda **kwargs: (_ for _ in ()).throw(RuntimeError("audit unavailable")))
    code = hashlib.sha256(f"{user.pk}:{user.username}".encode()).hexdigest()[:6]
    assert client.post("/api/auth/recovery/verify/", {"recovery_id": challenge.pk, "code": code}).status_code == 503
    user.refresh_from_db()
    assert user.totp_enrolled
