apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ehr-staging
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "20", argocd.argoproj.io/sync-options: PruneLast=true}
spec:
  project: ehr
  source: {repoURL: https://github.com/example/ehr.git, targetRevision: main, path: platform/helm/ehr, helm: {valueFiles: [values-staging.yaml]}}
  destination: {server: https://kubernetes.default.svc, namespace: ehr-staging}
  syncPolicy: {automated: {prune: true, selfHeal: true, allowEmpty: false}, syncOptions: [CreateNamespace=true, PruneLast=true]}
