// type-10022026-Maurice: Minimal role-scoped post-login shell.
import { StrictMode, type FormEvent } from "react";
import { createRoot } from "react-dom/client";
import { logout, roleShellTitle, type Role } from "./auth";
import { useEffect, useState } from "react";
import "./styles.css";
import { roleWorkspacePath } from "./workflow";
import { acknowledgeMedication, cancelJob, createAdminUser, createDevice, createMedication, createFamilyHistory, evaluateMedication, fetchAdminUsers, fetchAudit, fetchDeviceHistory, fetchFamilyHistory, fetchInteractionAdmin, fetchJobs, fetchMedicationHistory, fetchMedications, fetchPatient, fetchPatients, previewDevice, requestPatientExport, requestPopulationExport, fetchPopulationExports, populationExportAction, signMedication, updateAdminUser, updateSeverityFloor, fetchQuestionnaires, saveQuestionnaireResponse, fetchQuestionnaireReviewQueue, reviewQuestionnaireResponse, fetchAmendments, fetchAmendmentQueue, createAmendment, reviewAmendment, startAmendmentReview, requestBreakGlass, revokeBreakGlass, selectPatient, fetchDirectArtifacts, fetchDirectDeliveries, createDirectDelivery, cancelDirectDelivery, retryDirectDelivery, invokeCDS, actOnCDSCard, type AdminUser, type AuditEvent, type DeviceParsePreview, type DeviceVersion, type FamilyHistoryVersion, type InteractionEvaluation, type MedicationOrder, type MedicationVersion, type PatientRecord, type PatientExport, type InteractionRule, type JobStatus, type Questionnaire, type QuestionnaireResponse, type PatientAmendment, type BreakGlassGrant, type PopulationExport, type DirectArtifact, type DirectDelivery, type CDSCard } from "./records";

function Login({ onSuccess }: { onSuccess: (role: Role, username: string) => void }) {
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [passkeyOptions, setPasskeyOptions] = useState<any>(null);
  const [passkeyUnsupported, setPasskeyUnsupported] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setBusy(true); setError("");
    const values = Object.fromEntries(new FormData(event.currentTarget).entries());
    fetch("/api/auth/login/", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) })
      .then(async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail ?? "Unable to sign in; check credentials and TOTP."); return body; })
      .then((body) => { if (body.mfa === "webauthn") { setPasskeyOptions(body.options); setPasskeyUnsupported(!(window.PublicKeyCredential && navigator.credentials)); return; } onSuccess(body.role as Role, String(values.username)); })
      .catch((reason: Error) => setError(reason.message)).finally(() => setBusy(false));
  };
  const usePasskey = async () => { if (!passkeyOptions || !navigator.credentials) return; setBusy(true); try { const decode = (v: string) => Uint8Array.from(atob(v.replace(/-/g, "+").replace(/_/g, "/") + "=="), c => c.charCodeAt(0)); const publicKey = { ...passkeyOptions, challenge: decode(passkeyOptions.challenge), allowCredentials: passkeyOptions.allowCredentials?.map((c: any) => ({ ...c, id: decode(c.id) })) }; const assertion: any = await navigator.credentials.get({ publicKey }); const response = assertion.response; const body = { challenge: passkeyOptions.challenge, credential: { id: assertion.id, rawId: btoa(String.fromCharCode(...new Uint8Array(assertion.rawId))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, ""), type: assertion.type, response: { clientDataJSON: btoa(String.fromCharCode(...new Uint8Array(response.clientDataJSON))), authenticatorData: btoa(String.fromCharCode(...new Uint8Array(response.authenticatorData))), signature: btoa(String.fromCharCode(...new Uint8Array(response.signature))), userHandle: response.userHandle ? btoa(String.fromCharCode(...new Uint8Array(response.userHandle))) : null } } }; const result = await fetch("/api/auth/passkeys/login/", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await result.json(); if (!result.ok) throw new Error(data.detail ?? "Passkey verification failed."); onSuccess(data.role as Role, String(new FormData((document.querySelector("form") as HTMLFormElement)).get("username"))); } catch (reason) { setError(reason instanceof Error ? reason.message : "Passkey verification failed."); } finally { setBusy(false); } };
  return <main><h1>EHR demo sign in</h1><p role="note"><strong>Synthetic data only.</strong> Never use real credentials or patient data.</p><form onSubmit={submit} aria-label="Sign in"><label>Username <input name="username" autoComplete="username" required /></label><label>Password <input name="password" type="password" autoComplete="current-password" required /></label><label>Current TOTP code <input name="otp" inputMode="numeric" pattern="[0-9]{6}" aria-describedby="totp-help" /></label><small id="totp-help">Use TOTP when no enrolled passkey is available.</small><button disabled={busy}>{busy ? "Signing in…" : "Sign in"}</button>{passkeyOptions && !passkeyUnsupported && <button type="button" onClick={usePasskey} disabled={busy}>Use enrolled passkey</button>}{passkeyUnsupported && <p role="status">Passkeys are not supported in this browser. Use your TOTP code.</p>}{error && <p role="alert">{error}</p>}</form></main>;
}

function Header({ role, username, navigate }: { role: Role; username: string; navigate: (path: string) => void }) {
  const [credentials, setCredentials] = useState<any[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/auth/passkeys/", { credentials: "include" }).then(r => r.ok ? r.json() : []).then(setCredentials).catch(() => setMessage("Unable to load passkeys.")); }, []);
  const revoke = (id: number) => fetch(`/api/auth/passkeys/${id}/`, { method: "DELETE", credentials: "include" }).then(() => setCredentials(items => items.filter(item => item.id !== id))).catch(() => setMessage("Unable to revoke passkey."));
  return <header><h1>EHR demo</h1><p>{roleShellTitle(role)} · {username}</p><nav aria-label="Workspace navigation"><button onClick={() => navigate("/")}>Records</button>{role === "admin" && <button onClick={() => navigate("/admin")}>Administration</button>}{role === "developer" && <button onClick={() => navigate("/developer")}>SMART developer</button>}<button onClick={() => logout().then(() => window.location.reload())}>Sign out</button></nav><details><summary>Passkey and recovery settings</summary><section aria-label="Passkey management"><h2>Enrolled passkeys</h2>{!(window.PublicKeyCredential && navigator.credentials) && <p role="status">Passkeys are unsupported here; retain TOTP as your fallback.</p>}{credentials.length === 0 ? <p>No passkeys enrolled.</p> : <ul>{credentials.map(item => <li key={item.id}>{item.name} <button onClick={() => revoke(item.id)} aria-label={`Revoke ${item.name}`}>Revoke</button></li>)}</ul>}<button onClick={() => setMessage("Start passkey enrollment from a supported HTTPS browser.")} disabled={!(window.PublicKeyCredential && navigator.credentials)}>Enroll a new passkey</button>{message && <p role="alert">{message}</p>}</section><section aria-label="SMS recovery"><h2>SMS recovery</h2><p>Recovery is rate-limited and forces MFA re-enrollment. Codes are never displayed or stored in this browser.</p></section></details></header>;
}

export function PatientSelectionPanel() {
  const [mode, setMode] = useState<"identifier" | "name">("identifier");
  const [result, setResult] = useState<{ patient_id: string; request_id: string } | null>(null);
  const [state, setState] = useState<"idle" | "loading" | "error">("idle");
  const [error, setError] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); setState("loading"); setError(""); setResult(null);
    const values = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>;
    const payload: Record<string, string> = mode === "identifier" ? { identifier: values.identifier, birth_date: values.birth_date } : { given_name: values.given_name, family_name: values.family_name, birth_date: values.birth_date };
    selectPatient(payload).then(setResult).catch((reason: Error) => { setError(reason.message); setState("error"); }).finally(() => setState((current) => current === "error" ? current : "idle"));
  };
  return <section aria-labelledby="patient-selection-title"><h3 id="patient-selection-title">Patient selection test panel</h3><p role="note">Least privilege: this panel returns only an opaque FHIR Patient ID and request ID. It never displays demographics or stores browser data.</p><label>Lookup method <select value={mode} onChange={(event) => { setMode(event.target.value as typeof mode); setResult(null); setError(""); }}><option value="identifier">Identifier + date of birth</option><option value="name">Full given/family name + date of birth</option></select></label><form onSubmit={submit} aria-label="Patient selection"><p><strong>Warning:</strong> enter synthetic fixture values only.</p>{mode === "identifier" ? <label>Identifier <input name="identifier" required maxLength={64} autoComplete="off" /></label> : <><label>Given name <input name="given_name" required maxLength={80} autoComplete="off" /></label><label>Family name <input name="family_name" required maxLength={80} autoComplete="off" /></label></>}<label>Date of birth <input name="birth_date" type="date" required /></label><button disabled={state === "loading"}>{state === "loading" ? "Selecting…" : "Select patient"}</button>{state === "loading" && <p role="status">Selection in progress…</p>}{error && <p role="alert">{error}</p>}{result && <p role="status">Selection succeeded. Opaque Patient ID: <code>{result.patient_id}</code>. Request ID: <code>{result.request_id}</code></p>}</form></section>;
}

function PopulationExportPanel() {
  const [items, setItems] = useState<PopulationExport[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { fetchPopulationExports().then(setItems).catch(() => setError("Unable to load population export status.")); }, []);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const data = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>; requestPopulationExport({ ...data, cap: Number(data.cap) }, crypto.randomUUID()).then((item) => setItems((current) => [{ ...item, format: data.format as "csv" | "jsonl" }, ...current])).catch((reason: Error) => setError(reason.message)).finally(() => setBusy(false)); };
  return <section aria-label="Population exports"><h2>Authorized population exports</h2><p role="note"><strong>Warning:</strong> all-patient synthetic demo scope only. Never use real clinical data.</p><form onSubmit={submit}><input type="hidden" name="scope" value="all-demo" /><label>Start date <input name="start_date" type="date" required /></label><label>End date <input name="end_date" type="date" required /></label><label>Purpose <input name="purpose" minLength={10} maxLength={500} required /></label><label>Format <select name="format" defaultValue="jsonl"><option value="jsonl">Machine JSONL</option><option value="csv">Human CSV</option></select></label><label>Cap <input name="cap" type="number" min="0" defaultValue="10000" /></label><label>Schedule <select name="cadence" defaultValue="once"><option value="once">Run once</option><option value="daily">Daily (UTC)</option><option value="weekly">Weekly (UTC)</option></select></label><button disabled={busy}>{busy ? "Queueing…" : "Queue export"}</button></form>{error && <p role="alert">{error}</p>}{items.length === 0 ? <p>No population exports yet.</p> : <ul>{items.map((item) => <li key={item.id ?? item.job_id}>{item.format} · {item.state} {item.id && ["queued", "running"].includes(item.state) && <button onClick={() => populationExportAction(item.id!, "cancel").then((updated) => setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry))).catch(() => setError("Unable to cancel export."))}>Cancel</button>}{item.download_url && <a href={item.download_url}>Download</a>}</li>)}</ul>}</section>;
}

function CcdaReconciliationPanel({ patientId }: { patientId: string }) {
  const [status, setStatus] = useState(""); const [candidates, setCandidates] = useState<any[]>([]);
  const run = (path: string, init?: RequestInit) => fetch(path, { ...init, credentials: "include" }).then(async r => { const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error(b.detail ?? "C-CDA operation failed."); return b; });
  const exportCcda = () => run(`/api/patients/${patientId}/ccda/export/`, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() } }).then(j => setStatus(`Export ${j.state}; poll job ${j.id}.`)).catch(e => setStatus(e.message));
  const importCcda = (file: File) => file.arrayBuffer().then(body => run(`/api/patients/${patientId}/ccda/import/`, { method: "POST", body, headers: { "Idempotency-Key": crypto.randomUUID(), "Content-Type": "application/xml" } })).then(j => setStatus(`Import ${j.state}; candidates will appear after processing.`)).catch(e => setStatus(e.message));
  const decide = (id: number, decision: string) => run(`/api/ccda/candidates/${id}/decision/`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ decision }) }).then(() => setCandidates(items => items.map(i => i.id === id ? { ...i, state: decision } : i))).catch(e => setStatus(e.message));
  return <section aria-label="C-CDA transition and reconciliation"><h3>C-CDA transition</h3><p>Bounded, review-only import/export. Imported data never updates the chart automatically.</p><button onClick={exportCcda}>Queue deterministic export</button><label>Import C-CDA file <input type="file" accept="application/xml,.xml" onChange={e => e.target.files?.[0] && importCcda(e.target.files[0])} /></label><button onClick={() => setStatus("Refresh candidates from the document status endpoint after import.")}>Refresh reconciliation</button>{status && <p role="status">{status}</p>}{candidates.length > 0 && <ul>{candidates.map(c => <li key={c.id}>{c.section} · {c.resource_type} · {c.state} {c.state === "pending" && <><button onClick={() => decide(c.id, "accepted")}>Accept</button><button onClick={() => decide(c.id, "deferred")}>Defer</button></>}</li>)}</ul>}</section>;
}

function DirectDeliveryPanel({ patientId }: { patientId: string }) {
  const [artifacts, setArtifacts] = useState<DirectArtifact[]>([]); const [items, setItems] = useState<DirectDelivery[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([fetchDirectArtifacts(patientId), fetchDirectDeliveries()]).then(([a, d]) => { setArtifacts(a); setItems(d); }).catch(() => setError("Unable to load simulated Direct delivery status.")); }, [patientId]);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); createDirectDelivery({ artifact_id: Number(form.artifact_id), recipient: String(form.recipient), purpose: String(form.purpose) }, crypto.randomUUID()).then((item) => setItems((current) => [item, ...current])).catch((e: Error) => setError(e.message)).finally(() => setBusy(false)); };
  return <section aria-label="Direct delivery"><h3>Direct delivery (local simulation)</h3><p role="note"><strong>Simulation only:</strong> no SMTP, Direct network, or real message is sent. Use synthetic recipients only; C-CDA bytes and recipient addresses are never displayed after submission.</p><form onSubmit={submit}><label>C-CDA TransitionDocument <select name="artifact_id" required defaultValue=""><option value="" disabled>Select an unexpired artifact</option>{artifacts.map((a) => <option key={a.id} value={a.id}>Document {a.id} · {a.template_version} · {a.size_bytes} bytes</option>)}</select></label><label>Direct-style recipient <input name="recipient" type="email" maxLength={255} autoComplete="off" required /></label><label>Purpose (10–240 characters) <input name="purpose" minLength={10} maxLength={240} required /></label><button disabled={busy || artifacts.length === 0}>{busy ? "Queueing…" : "Queue simulated delivery"}</button></form>{error && <p role="alert">{error}</p>}<h4>Delivery status</h4>{items.length === 0 ? <p>No deliveries yet.</p> : <ul>{items.map((item) => <li key={item.id}><span>{item.state} · {item.attempts}/{item.max_attempts}</span>{item.state === "queued" || item.state === "sending" ? <button onClick={() => cancelDirectDelivery(item.id).then((updated) => setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry))).catch(() => setError("Unable to cancel delivery."))}>Cancel</button> : item.state === "failed" ? <button onClick={() => retryDirectDelivery(item.id).then((updated) => setItems((current) => current.map((entry) => entry.id === updated.id ? updated : entry))).catch(() => setError("Unable to retry delivery."))}>Retry</button> : null}</li>)}</ul>}</section>;
}

function CDSCardsPanel({ patientId }: { patientId: string }) {
  const [cards, setCards] = useState<CDSCard[]>([]); const [message, setMessage] = useState("");
  const run = () => { setMessage(""); invokeCDS("demo-patient-view", patientId).then(setCards).catch(() => setMessage("CDS demo unavailable; no clinical decision was made.")); };
  const act = (card: CDSCard, action: "accept" | "dismiss" | "override") => { const reason = action === "dismiss" || action === "override" ? window.prompt("Reason (required)") ?? "" : ""; actOnCDSCard(card.uuid, action, action === "accept" ? card.suggestions[0]?.id ?? "" : "", reason).then(() => setCards(items => items.filter(item => item.uuid !== card.uuid))).catch((error: Error) => setMessage(error.message)); };
  return <section aria-label="CDS demo cards"><h3>Decision support cards</h3><p role="note"><strong>Non-clinical demo:</strong> cards are reminders only, never silently change the chart, and show safe evidence links.</p><button onClick={run}>Evaluate local demo rules</button>{message && <p role="alert">{message}</p>}{cards.length === 0 ? <p role="status">No decision support cards.</p> : <ul>{cards.map(card => <li key={card.uuid} data-indicator={card.indicator}><article><h4>{card.summary}</h4><p>{card.detail}</p><p>Severity: {card.indicator} · <a href={card.source.url}>Evidence: {card.source.label}</a></p><button onClick={() => act(card, "accept")}>Accept suggestion</button><button onClick={() => act(card, "dismiss")}>Dismiss</button><button onClick={() => act(card, "override")}>Override</button></article></li>)}</ul>}</section>;
}

function App() {
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [username, setUsername] = useState("");
  const [patients, setPatients] = useState<PatientRecord[]>([]);
  const [selected, setSelected] = useState<PatientRecord | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [audit, setAudit] = useState<AuditEvent[]>([]);
  const [role, setRole] = useState<Role>("patient");
  const [route, setRoute] = useState(window.location.pathname);
  const [medications, setMedications] = useState<MedicationOrder[]>([]);
  const [medicationHistory, setMedicationHistory] = useState<MedicationVersion[]>([]);
  const [medicationError, setMedicationError] = useState("");
  const [savingMedication, setSavingMedication] = useState(false);
  const [exportFormat, setExportFormat] = useState<"json" | "pdf">("json");
  const [exportState, setExportState] = useState<PatientExport | null>(null);
  const [exportError, setExportError] = useState("");
  const [exportLoading, setExportLoading] = useState(false);
  const [evaluations, setEvaluations] = useState<Record<number, InteractionEvaluation>>({});
  const [acknowledged, setAcknowledged] = useState<Record<number, boolean>>({});
  const [adminUsers, setAdminUsers] = useState<AdminUser[]>([]);
  const [rules, setRules] = useState<InteractionRule[]>([]);
  const [severityFloor, setSeverityFloor] = useState<"LOW" | "MODERATE" | "HIGH">("LOW");
  const [adminError, setAdminError] = useState("");
  const [newUser, setNewUser] = useState({ username: "", password: "", role: "patient" as AdminUser["role"] });
  const [jobs, setJobs] = useState<JobStatus[]>([]);
  const [familyHistory, setFamilyHistory] = useState<FamilyHistoryVersion[]>([]);
  const [familyHistoryError, setFamilyHistoryError] = useState("");
  const [familyHistoryLoading, setFamilyHistoryLoading] = useState(false);
  const [devicePreview, setDevicePreview] = useState<DeviceParsePreview | null>(null);
  const [deviceError, setDeviceError] = useState("");
  const [deviceHistory, setDeviceHistory] = useState<DeviceVersion[]>([]);
  const [questionnaires, setQuestionnaires] = useState<Questionnaire[]>([]);
  const [questionnaireError, setQuestionnaireError] = useState("");
  const [reviewQueue, setReviewQueue] = useState<QuestionnaireResponse[]>([]);
  const [amendments, setAmendments] = useState<PatientAmendment[]>([]);
  const [amendmentQueue, setAmendmentQueue] = useState<PatientAmendment[]>([]);
  const [amendmentError, setAmendmentError] = useState("");
  const [breakGlass, setBreakGlass] = useState<BreakGlassGrant | null>(null);
  const [breakGlassReason, setBreakGlassReason] = useState("");
  const [breakGlassError, setBreakGlassError] = useState("");
  const isAdmin = role === "admin";
  useEffect(() => {
    fetch("/api/auth/session/", { credentials: "include" }).then((response) => response.ok ? response.json() : null).then((session) => {
      if (session?.role) { setRole(session.role as Role); setUsername(session.username ?? ""); setAuthenticated(true); }
      else setAuthenticated(false);
    }).catch(() => setAuthenticated(false));
  }, []);
  useEffect(() => {
    if (authenticated && role !== "developer") fetchPatients().then(setPatients).catch(() => setError("Unable to load synthetic patients; try again.")).finally(() => setLoading(false));
    else if (authenticated) setLoading(false);
  }, [authenticated, role]);
  useEffect(() => { if (isAdmin) { fetchAudit().then(setAudit).catch(() => setAdminError("Unable to load audit evidence; re-authenticate.")); fetchAdminUsers().then(setAdminUsers).catch(() => setAdminError("Unable to load administrator users.")); fetchInteractionAdmin().then((settings) => { setRules(settings.rules); setSeverityFloor(settings.severity_floor); }).catch(() => setAdminError("Unable to load safety settings.")); fetchJobs().then(setJobs).catch(() => setAdminError("Unable to load job status.")); const timer = window.setInterval(() => fetchJobs().then(setJobs).catch(() => undefined), 3000); return () => window.clearInterval(timer); } }, [isAdmin]);
  useEffect(() => { if (authenticated) fetchQuestionnaires().then(setQuestionnaires).catch(() => setQuestionnaireError("Unable to load questionnaires; re-authenticate.")); if (role === "clinician") { fetchQuestionnaireReviewQueue().then(setReviewQueue).catch(() => setQuestionnaireError("Unable to load review queue.")); fetchAmendmentQueue().then(setAmendmentQueue).catch(() => setAmendmentError("Unable to load amendment review queue.")); } }, [authenticated, role]);
  const navigate = (next: string) => { window.history.pushState({}, "", next); setRoute(next); setSelected(null); };
  if (authenticated === null) return <main aria-busy="true"><p role="status">Loading secure session…</p></main>;
  if (!authenticated) return <Login onSuccess={(nextRole, nextUsername) => { setRole(nextRole); setUsername(nextUsername); setAuthenticated(true); }} />;
   if (route === roleWorkspacePath("developer")) return <main><Header role={role} username={username} navigate={navigate} /><section aria-labelledby="developer-title"><h2 id="developer-title">Developer SMART workspace</h2><p>Use registered SMART credentials and a current MFA-authenticated token. Selection accepts an exact identifier or exact normalized full name plus date of birth.</p><p role="note"><strong>Warning:</strong> synthetic data only. Tokens and submitted demographics are never stored in browser storage.</p><PatientSelectionPanel /></section></main>;
  const openPatient = (id: string) => { setLoading(true); setError(""); setFamilyHistoryLoading(true); fetchPatient(id).then((record) => { setSelected(record); return Promise.all([fetchMedications(id).then(setMedications), fetchFamilyHistory(id).then(setFamilyHistory), fetchAmendments(id).then(setAmendments)]); }).catch(() => setError("Unable to load this synthetic record.")).finally(() => { setLoading(false); setFamilyHistoryLoading(false); }); };
  const submitMedication = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!selected || role !== "clinician") return; setSavingMedication(true); setMedicationError(""); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form.entries()) as Record<string, string | number>; payload.dose = Number(payload.dose); payload.quantity = Number(payload.quantity); payload.refills = Number(payload.refills); createMedication(selected.public_id, payload).then((order) => { setMedications((current) => [...current, order]); event.currentTarget.reset(); }).catch(() => setMedicationError("Unable to save draft. No medication or audit event was created.")).finally(() => setSavingMedication(false)); };
  return <main>
     <Header role={role} username={username} navigate={navigate} /><p>{roleShellTitle(role)}</p>
    <aside role="note"><strong>Synthetic data only.</strong> This demo contains no real patient information.</aside>
    {loading && <p role="status">Loading patient records…</p>}
     {error && <p role="alert">{error}</p>}
     {breakGlass?.state === "active" && <aside role="alert" aria-label="Emergency access banner"><strong>EMERGENCY BREAK-GLASS ACTIVE</strong> — read-only access expires {breakGlass.expires_at}. <button onClick={() => revokeBreakGlass(breakGlass.patient).then(() => setBreakGlass({ ...breakGlass, state: "revoked" })).catch(() => setBreakGlassError("Unable to revoke emergency access."))}>Revoke</button></aside>}
    {!loading && !error && !selected && patients.length === 0 && <p>No synthetic patients found.</p>}
    {!selected && patients.map((patient) => <button key={patient.public_id} onClick={() => openPatient(patient.public_id)}>{patient.display_name}</button>)}
      {isAdmin && <PopulationExportPanel />}
      {isAdmin && <section aria-label="Audit viewer"><h2>Audit trail</h2><p>Administrator-only, append-only evidence.</p><table><thead><tr><th>UTC time</th><th>Actor</th><th>Action</th><th>Patient</th><th>Current hash</th></tr></thead><tbody>{audit.map((event) => <tr key={event.sequence}><td>{event.occurred_at}</td><td>{event.actor}</td><td>{event.action}</td><td>{event.patient ?? "—"}</td><td>{event.current_hash}</td></tr>)}</tbody></table></section>}
      {isAdmin && <section aria-label="Job status"><h2>Background jobs</h2><p role="status">Status refreshes every 3 seconds. Only lifecycle metadata is shown.</p><table><thead><tr><th>Job</th><th>State</th><th>Attempts</th><th>Dependency</th><th>Action</th></tr></thead><tbody>{jobs.map((job) => <tr key={job.id}><td>{job.id}</td><td>{job.state}</td><td>{job.attempts}/{job.max_attempts}</td><td>{job.dependency}</td><td>{["queued", "running"].includes(job.state) && <button onClick={() => cancelJob(job.id).then((updated) => setJobs((items) => items.map((item) => item.id === updated.id ? updated : item))).catch(() => setAdminError("Unable to cancel job."))}>Cancel</button>}</td></tr>)}</tbody></table></section>}
     {isAdmin && <section aria-label="Administration"><h2>Administration</h2>{adminError && <p role="alert">{adminError}</p>}<h3>Users</h3><form onSubmit={(event) => { event.preventDefault(); createAdminUser(newUser.username, newUser.password, newUser.role).then((user) => { setAdminUsers((items) => [...items, user]); setNewUser({ username: "", password: "", role: "patient" }); }).catch(() => setAdminError("Unable to create user.")); }}><input aria-label="New username" value={newUser.username} onChange={(event) => setNewUser({ ...newUser, username: event.target.value })} placeholder="Username" required /><input aria-label="Temporary password" type="password" value={newUser.password} onChange={(event) => setNewUser({ ...newUser, password: event.target.value })} placeholder="Temporary password" required /><select aria-label="New user role" value={newUser.role} onChange={(event) => setNewUser({ ...newUser, role: event.target.value as AdminUser["role"] })}><option value="patient">Patient</option><option value="clinician">Clinician</option><option value="admin">Administrator</option><option value="developer">Developer</option></select><button>Create user</button></form><table><thead><tr><th>User</th><th>Role</th><th>Active</th><th>Action</th></tr></thead><tbody>{adminUsers.map((user) => <tr key={user.id}><td>{user.username}</td><td><select aria-label={`Role for ${user.username}`} value={user.role} onChange={(event) => updateAdminUser(user.id, { role: event.target.value as AdminUser["role"] }).then((next) => setAdminUsers((items) => items.map((item) => item.id === next.id ? next : item))).catch(() => setAdminError("Unable to update user."))}><option value="patient">Patient</option><option value="clinician">Clinician</option><option value="admin">Administrator</option><option value="developer">Developer</option></select></td><td>{user.is_active ? "Active" : "Inactive"}</td><td><button onClick={() => updateAdminUser(user.id, { is_active: !user.is_active }).then((next) => setAdminUsers((items) => items.map((item) => item.id === next.id ? next : item))).catch(() => setAdminError("Unable to update user."))}>{user.is_active ? "Deactivate" : "Activate"}</button></td></tr>)}</tbody></table><h3>Interaction safety</h3><label>Minimum alert severity <select value={severityFloor} onChange={(event) => { const next = event.target.value as "LOW" | "MODERATE" | "HIGH"; updateSeverityFloor(next).then(() => setSeverityFloor(next)).catch(() => setAdminError("Unable to update safety floor.")); }}><option value="LOW">Low</option><option value="MODERATE">Moderate</option><option value="HIGH">High</option></select></label><ul>{rules.map((rule) => <li key={rule.id}>{rule.severity}: {rule.description} ({rule.active ? "active" : "inactive"})</li>)}</ul></section>}
       {role === "clinician" && <section aria-label="Questionnaire review queue"><h2>Questionnaire review queue</h2>{questionnaireError && <p role="alert">{questionnaireError}</p>}{reviewQueue.length === 0 ? <p>No submitted responses awaiting review.</p> : reviewQueue.map((item) => <article key={item.id}><h3>Response {item.id}</h3><p>Submitted for clinician review.</p><button onClick={() => reviewQuestionnaireResponse(item.id, "accepted").then(() => setReviewQueue((items) => items.filter((entry) => entry.id !== item.id))).catch(() => setQuestionnaireError("Unable to review response."))}>Accept</button><button onClick={() => reviewQuestionnaireResponse(item.id, "returned", "Please clarify the submitted answers.").then(() => setReviewQueue((items) => items.filter((entry) => entry.id !== item.id))).catch(() => setQuestionnaireError("Unable to return response."))}>Return</button></article>)}</section>}
       {role === "clinician" && <section aria-label="Patient amendment review queue"><h2>Patient amendment review queue</h2>{amendmentError && <p role="alert">{amendmentError}</p>}{amendmentQueue.length === 0 ? <p>No amendment requests awaiting review.</p> : amendmentQueue.map((item) => <article key={item.id}><h3>{item.resource_type} amendment</h3><p>Status: {item.status}{item.overdue ? " · overdue" : ""}</p>{item.status === "submitted" ? <button onClick={() => startAmendmentReview(item.id).then((updated) => setAmendmentQueue((items) => items.map((entry) => entry.id === updated.id ? updated : entry))).catch(() => setAmendmentError("Unable to start amendment review."))}>Start review</button> : <><button onClick={() => reviewAmendment(item.id, "accepted").then(() => setAmendmentQueue((items) => items.filter((entry) => entry.id !== item.id))).catch(() => setAmendmentError("Unable to accept amendment."))}>Accept</button><button onClick={() => reviewAmendment(item.id, "appended", "The original record is preserved and this clarification is linked alongside it.").then(() => setAmendmentQueue((items) => items.filter((entry) => entry.id !== item.id))).catch(() => setAmendmentError("Unable to append amendment."))}>Append</button><button onClick={() => reviewAmendment(item.id, "denied", "The requested correction is not supported by the source evidence.").then(() => setAmendmentQueue((items) => items.filter((entry) => entry.id !== item.id))).catch(() => setAmendmentError("Unable to deny amendment."))}>Deny</button></>}</article>)}</section>}
        {selected && <section aria-label="Patient record"><button onClick={() => setSelected(null)}>Back</button><h2>{selected.display_name}</h2>{role === "clinician" && <CDSCardsPanel patientId={selected.public_id} />} {role === "clinician" && <DirectDeliveryPanel patientId={selected.public_id} />} {role === "clinician" && <section aria-label="Emergency break-glass"><h3>Emergency read access</h3><p>Read-only for 30 minutes; no renewal. Reason is visible only to administrators.</p><textarea aria-label="Emergency reason" minLength={20} maxLength={500} value={breakGlassReason} onChange={(event) => setBreakGlassReason(event.target.value)} /><button onClick={() => requestBreakGlass(selected.public_id, breakGlassReason).then(setBreakGlass).catch((reason: Error) => setBreakGlassError(reason.message))}>Request emergency access</button>{breakGlassError && <p role="alert">{breakGlassError}</p>}</section>}
       {role === "clinician" && <CcdaReconciliationPanel patientId={selected.public_id} />}
      <p>Race: {selected.race} · Ethnicity: {selected.ethnicity} · Language: {selected.preferred_language}</p>
      <p>Sex: {selected.sex} · Sexual orientation: {selected.sexual_orientation} · Gender identity: {selected.gender_identity}</p>
       <p>Birth date: {selected.birth_date} · Death date: {selected.death_date ?? "Not recorded"}</p>
        <section aria-label="Patient amendment requests"><h3>Request a record amendment</h3>{amendmentError && <p role="alert">{amendmentError}</p>}{amendments.length === 0 ? <p>No amendment requests.</p> : <ul>{amendments.map((item) => <li key={item.id}>{item.resource_type} · {item.status} · due {item.due_at}{item.overdue ? " · overdue" : ""}</li>)}</ul>}{role === "patient" && <form onSubmit={(event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); createAmendment(selected.public_id, { resource_type: String(form.resource_type), resource_id: String(form.resource_id), source_version: Number(form.source_version), reason: String(form.reason) }).then((item) => { setAmendments((items) => [...items, item]); setAmendmentError(""); event.currentTarget.reset(); }).catch((error: Error) => setAmendmentError(error.message)); }}><label>Resource type <select name="resource_type" defaultValue="Patient"><option>Patient</option><option>FamilyMemberHistory</option><option>Device</option><option>MedicationRequest</option><option>QuestionnaireResponse</option></select></label><label>Resource id <input name="resource_id" required /></label><label>Source version <input name="source_version" type="number" min="1" defaultValue="1" required /></label><label>Reason (20–500 characters) <textarea name="reason" minLength={20} maxLength={500} required /></label><button>Submit amendment request</button></form>}</section>
       <section aria-label="Patient record download"><h3>Download synthetic record</h3><label>Format <select value={exportFormat} onChange={(event) => setExportFormat(event.target.value as "json" | "pdf")}><option value="json">JSON + data dictionary</option><option value="pdf">PDF (non-clinical)</option></select></label><button disabled={exportLoading} onClick={() => { setExportError(""); setExportState(null); setExportLoading(true); requestPatientExport(selected.public_id, exportFormat).then(setExportState).catch((error: Error) => setExportError(error.message)).finally(() => setExportLoading(false)); }}>{exportLoading ? "Preparing…" : "Create download"}</button>{exportError && <p role="alert">{exportError}</p>}{exportState && <p role="status">Ready. SHA-256: {exportState.sha256}. Expires: {exportState.expires_at}. <a href={exportState.download_url}>Download</a></p>}</section>
       <section aria-label="Questionnaire form"><h3>Questionnaires</h3>{questionnaireError && <p role="alert">{questionnaireError}</p>}{questionnaires.length === 0 ? <p>No active questionnaires found.</p> : questionnaires.map((questionnaire) => <form key={questionnaire.id} onSubmit={(event) => { event.preventDefault(); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); const answers = Object.fromEntries(questionnaire.items.filter((item) => form[item.link_id] !== "").map((item) => [item.link_id, item.item_type === "boolean" ? form[item.link_id] === "true" : item.item_type === "integer" ? Number(form[item.link_id]) : form[item.link_id]])); saveQuestionnaireResponse(selected.public_id, { questionnaire_id: questionnaire.id, questionnaire_version: questionnaire.version, answers, status: "submitted" }).then(() => setQuestionnaireError("Response submitted for clinician review.")).catch((error: Error) => setQuestionnaireError(error.message)); }}><h4>{questionnaire.title} (v{questionnaire.version})</h4>{questionnaire.items.map((item) => <label key={item.link_id}>{item.text}<input name={item.link_id} type={item.item_type === "date" ? "date" : item.item_type === "integer" || item.item_type === "decimal" ? "number" : "text"} required={item.required} min={item.min_value ?? undefined} max={item.max_value ?? undefined} maxLength={item.max_length ?? undefined} />{item.options.length > 0 && <small>Options: {item.options.map((option) => typeof option === "string" ? option : option.value).join(", ")}</small>}</label>)}<button type="submit">Submit response</button></form>)}</section>
       <h3>Allergies</h3><ul>{selected.allergies.map((item) => <li key={String(item.code)}>{item.label}</li>)}</ul>
      <h3>Conditions</h3><ul>{selected.conditions.map((item) => <li key={String(item.code)}>{item.label}</li>)}</ul>
      <h3>Observations</h3><ul>{selected.observations.map((item) => <li key={String(item.code)}>{item.label}: {item.value} {item.unit}</li>)}</ul>
       <h3>Devices</h3><ul>{selected.devices.map((item) => <li key={String(item.device_id ?? item.code)}>{item.label} ({item.status}) {item.parse_status && <small>UDI {item.parse_status}</small>} {item.device_id && <button onClick={() => fetchDeviceHistory(selected.public_id, Number(item.device_id)).then(setDeviceHistory).catch(() => setDeviceError("Unable to load device history."))}>History</button>}</li>)}</ul>{deviceHistory.length > 0 && <section aria-label="Immutable device history"><h4>Immutable device history</h4><ol>{deviceHistory.map((version) => <li key={version.id}>v{version.version} · {version.label} · {version.status} · {version.parse_status}</li>)}</ol></section>}{role === "clinician" && <form aria-label="Device UDI form" onSubmit={(event) => { event.preventDefault(); setDeviceError(""); const form = Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string, string>; createDevice(selected.public_id, form).then(() => fetchPatient(selected.public_id).then(setSelected)).then(() => { setDevicePreview(null); event.currentTarget.reset(); }).catch((reason: Error) => setDeviceError(reason.message)); }}><label>UDI <input name="udi" required onChange={(event) => previewDevice(selected.public_id, event.target.value).then(setDevicePreview).catch(() => setDevicePreview(null))} /></label><label>Code <input name="code" defaultValue="UDI" required /></label><label>Label <input name="label" defaultValue="Implantable device" required /></label><label>Status <select name="status" defaultValue="active"><option value="active">Active</option><option value="inactive">Inactive</option><option value="entered-in-error">Entered in error</option></select></label><button>Save device</button>{devicePreview && <p role="status">Parser: {devicePreview.status} · {devicePreview.error_code || devicePreview.device_identifier || "review required"}</p>}{deviceError && <p role="alert">{deviceError}</p>}</form>}
        <h3>Family health history</h3>{familyHistoryLoading && <p role="status">Loading family history…</p>}{familyHistoryError && <p role="alert">{familyHistoryError}</p>}{!familyHistoryLoading && !familyHistoryError && familyHistory.length === 0 && <p>No family history entries found.</p>}<ul>{familyHistory.map((entry) => <li key={entry.id}>v{entry.version} · {entry.relationship} · {entry.condition_display} ({entry.status})</li>)}</ul>{role === "clinician" && <form aria-label="Family history form" onSubmit={(event) => { event.preventDefault(); setFamilyHistoryError(""); const form = Object.fromEntries(new FormData(event.currentTarget).entries()); createFamilyHistory(selected.public_id, form as Record<string, string>).then((entry) => { setFamilyHistory((items) => [...items, entry]); event.currentTarget.reset(); }).catch((reason: Error) => setFamilyHistoryError(reason.message)); }}><label>Relationship <select name="relationship" required><option value="mother">Mother</option><option value="father">Father</option><option value="sibling">Sibling</option><option value="child">Child</option></select></label><label>Relative sex <select name="relative_sex"><option value="unknown">Unknown</option><option value="female">Female</option><option value="male">Male</option></select></label><label>Condition code <input name="condition_code" required /></label><label>Condition system <input name="condition_system" defaultValue="http://snomed.info/sct" required /></label><label>Approved display <input name="condition_display" required /></label><label>Onset date <input name="onset_date" type="date" /></label><button>Save family history</button></form>}
       <h3>Medication orders</h3>
        {role === "clinician" && <form onSubmit={submitMedication} aria-label="Clinician medication draft form"><label>Medication code <input name="medication_code" required /></label><label>Name <input name="medication_name" required /></label><label>Dose <input name="dose" type="number" min="0.001" step="0.001" required /></label><label>Unit <input name="dose_unit" required /></label><label>Route <input name="route" required /></label><label>Frequency <input name="frequency" required /></label><label>Start date <input name="start_date" type="date" required /></label><label>Quantity <input name="quantity" type="number" min="0.001" step="0.001" required /></label><label>Refills <input name="refills" type="number" min="0" step="1" defaultValue="0" required /></label><label>Indication <input name="indication" required /></label><button disabled={savingMedication}>{savingMedication ? "Saving…" : "Save draft"}</button></form>}
       {medicationError && <p role="alert">{medicationError}</p>}
        {medications.length === 0 ? <p>No medication orders found.</p> : <ul>{medications.map((order) => <li key={order.id}><strong>{order.active_version?.medication_name}</strong> — {order.active_version?.status}<button onClick={() => fetchMedicationHistory(selected.public_id, order.id).then(setMedicationHistory).catch(() => setMedicationError("Unable to load medication history."))}>History</button>{role === "clinician" && order.active_version?.status === "draft" && <><button onClick={() => evaluateMedication(selected.public_id, order.id).then((evaluation) => setEvaluations((current) => ({ ...current, [order.id]: evaluation }))).catch(() => setMedicationError("Safety evaluation unavailable; signing is blocked."))}>Evaluate safety</button>{evaluations[order.id] && <section aria-label="Medication safety alerts"><ul>{evaluations[order.id].findings.map((finding) => <li key={finding.rule_id}>{finding.suppressed ? "Suppressed below floor" : `${finding.severity}: ${finding.description}`}</li>)}</ul>{evaluations[order.id].findings.some((finding) => !finding.suppressed && finding.severity !== "CRITICAL") && <button onClick={() => acknowledgeMedication(selected.public_id, order.id, evaluations[order.id].id).then(() => setAcknowledged((current) => ({ ...current, [order.id]: true }))).catch(() => setMedicationError("Unable to acknowledge safety alert."))}>Acknowledge</button>}<button disabled={evaluations[order.id].findings.some((finding) => finding.severity === "CRITICAL") || (evaluations[order.id].findings.some((finding) => !finding.suppressed) && !acknowledged[order.id])} onClick={() => signMedication(selected.public_id, order.id, evaluations[order.id].id, Boolean(acknowledged[order.id])).then((version) => setMedications((current) => current.map((item) => item.id === order.id ? { ...item, active_version: version } : item))).catch((error: Error) => setMedicationError(error.message))}>Sign safely</button></section>}</>}</li>)}</ul>}
       {medicationHistory.length > 0 && <section aria-label="Immutable medication history"><h4>Immutable history</h4><ol>{medicationHistory.map((version) => <li key={version.id}>v{version.version}: {version.medication_name}, {version.dose} {version.dose_unit}, {version.status}</li>)}</ol></section>}
     </section>}
  </main>;
}

if (document.getElementById("root")) createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
