# type-10022026-Maurice: Ticket 02 synthetic patient and read-only clinical schema.
# Generated by Django 5.2.17 on 2026-10-02 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=80)),
                ('race', models.CharField(choices=[('2106-3', 'White'), ('2054-5', 'Black or African American'), ('UNK', 'Unknown')], default='UNK', max_length=40)),
                ('ethnicity', models.CharField(choices=[('2186-5', 'Not Hispanic or Latino'), ('2135-2', 'Hispanic or Latino'), ('UNK', 'Unknown')], default='UNK', max_length=40)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('UNK', 'Unknown')], default='en', max_length=20)),
                ('sex', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('sexual_orientation', models.CharField(choices=[('straight', 'Straight'), ('gay', 'Gay or lesbian'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('gender_identity', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('non-binary', 'Non-binary'), ('unknown', 'Unknown')], default='unknown', max_length=30)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField(blank=True, null=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['public_id'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('value', models.CharField(max_length=120)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='users.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='users.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='users.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AllergyIntolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=120)),
                ('recorded_date', models.DateField(blank=True, null=True)),
                ('reaction', models.CharField(blank=True, max_length=120)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='users.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
