# Generated by Django 5.2.17 on 2026-10-02 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auditevent_append_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_orders', to='users.patient')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescribed_medications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationOrderVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('medication_code', models.CharField(max_length=80)),
                ('medication_name', models.CharField(max_length=160)),
                ('dose', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dose_unit', models.CharField(max_length=30)),
                ('route', models.CharField(max_length=40)),
                ('frequency', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('refills', models.PositiveIntegerField(default=0)),
                ('indication', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_versions_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='users.medicationorder')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='users.medicationorderversion')),
            ],
            options={
                'ordering': ['version'],
            },
        ),
        migrations.AddField(
            model_name='medicationorder',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for', to='users.medicationorderversion'),
        ),
        migrations.AddConstraint(
            model_name='medicationorderversion',
            constraint=models.UniqueConstraint(fields=('order', 'version'), name='med_order_version_unique'),
        ),
    ]
