# Generated by Django 5.2.17 on 2026-10-02 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_ticket03_family_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familyhistoryversion',
            options={'ordering': ['version']},
        ),
    ]
