from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    dependencies = [("users", "0022_ticket13_cds")]
    operations = [
        migrations.CreateModel(name="MeasureDefinition", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("url", models.CharField(max_length=240, unique=True)), ("title", models.CharField(max_length=200)), ("description", models.TextField(blank=True)), ("provenance", models.JSONField(default=dict)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="MeasureVersion", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("version", models.PositiveIntegerField()), ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("retired", "Retired")], default="draft", max_length=12)), ("effective_start", models.DateField()), ("effective_end", models.DateField(blank=True, null=True)), ("schema", models.JSONField()), ("provenance", models.JSONField(default=dict)), ("published_at", models.DateTimeField(blank=True, null=True)), ("measure", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="users.measuredefinition"))]),
        migrations.CreateModel(name="MeasureRun", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("period_start", models.DateField()), ("period_end", models.DateField()), ("snapshot_checksum", models.CharField(max_length=64)), ("status", models.CharField(default="queued", max_length=20)), ("created_at", models.DateTimeField(auto_now_add=True)), ("job", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="measure_run", to="users.job")), ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.measureversion"))]),
        migrations.CreateModel(name="MeasureReport", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("status", models.CharField(max_length=20)), ("period_start", models.DateField()), ("period_end", models.DateField()), ("snapshot_checksum", models.CharField(max_length=64)), ("populations", models.JSONField()), ("created_at", models.DateTimeField(auto_now_add=True)), ("measure", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.measuredefinition")), ("run", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="report", to="users.measurerun")), ("version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.measureversion"))]),
        migrations.AddConstraint(model_name="measureversion", constraint=models.UniqueConstraint(fields=("measure", "version"), name="measure_version_unique")),
    ]
